version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt
            - pylint --disable=C0103 simplecaesar.py
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
